apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-otel-collector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-collector-config
data:
  demo-collector.yaml: |
    receivers:
      k8s_cluster:
    processors:
      batch:
    exporters:
      logging:
      datadog:
        api:
          site: datadoghq.com
          key: ${env:DD_API_KEY}
    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        metrics:
          receivers: [k8s_cluster]
          processors: [batch]
          exporters: [logging, datadog]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-otel-collector
  template:
    metadata:
      labels:
        app: demo-otel-collector
    spec:
      serviceAccountName: demo-otel-collector
      containers:
        - name: otelcol
          args:
            - --config=/conf/demo-collector.yaml
          image: otel/opentelemetry-collector-contrib:0.83.0
          volumeMounts:
            - mountPath: /conf
              name: demo-collector-config
      volumes:
        - configMap:
            items:
              - key: demo-collector.yaml
                path: demo-collector.yaml
            name: demo-collector-config
          name: demo-collector-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-otel-collector
  labels:
    app: demo-otel-collector
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: demo-otel-collector
subjects:
  - kind: ServiceAccount
    name: demo-otel-collector
    namespace: beslogic-test